### ISSUE TITLE
Fragment shader failed to compile

### ISSUE THREAD

**Issue by Vuldraq** [HackerPoet/PySpace#1]
Upon running, I receive the following error message:

```
Compiling Vertex Shader...
Compiling Fragment Shader...
Fragment shader failed to compile with the following errors:
ERROR: 0:66: error(#132) Syntax error: "=" parse error
ERROR: error(#273) 1 compilation errors.  No code generated

Traceback (most recent call last):
  File "ray_marcher_demo.py", line 253, in <module>
    program = shader.compile(camera)
  File "shader.py", line 73, in compile
    program = self.compile_program(v_shader, f_shader)
  File "shader.py", line 106, in compile_program
    fragment_shader = self.compile_shader(fragment_source, GL_FRAGMENT_SHADER)
  File "shader.py", line 92, in compile_shader
    raise ValueError, 'Shader compilation failed'
ValueError: Shader compilation failed
```

No idea if i'm doing something wrong here, (still relatively new to coding and GitHub), although I haven't altered the file in any way, and have all the required dependencies, but thought i would bring it up anyway.

**Comment by HackerPoet** [comment]
Is this just running the demo app unmodified, or have you made changes?

Try uncommenting line 70 of 'shader.py' under where it says 'Debugging the shader'.  After running again, check the new 'frag_gen.glsl' file and see what the error looks like on line 66.

**Comment by Vuldraq** [comment]
Yes, this is using all the files unmodified, using the demo file, even after re-downloading the problem persists. 
After uncommenting that line of code, line 66 of the new 'frag_gen.glsl' file is:
`void planeFold(inout vec4 z, vec3 n, float d=0.0) {`
Here is the full method:
`void planeFold(inout vec4 z, vec3 n, float d=0.0) {
	z.xyz -= 2.0 * min(0.0, dot(z.xyz, n) - d) * n;
}`

**Comment by HackerPoet** [comment]
Found an identical issue here: https://community.amd.com/thread/167874
I guess this feature is not officially supported on all GLSL compilers.  I'll try to make a workaround for this.

**Comment by Nikateen** [comment]
<img width="387" alt="screenshot 2019-01-15 at 10 32 20 am" src="https://user-images.githubusercontent.com/46481850/51159764-d8ac6c00-18b0-11e9-8622-e1c71f125a00.png">

line 31 Is just a bunch of ####, I have pretty much the same error
 PySpace-master/pyspace/shader.py", line 92, in compile_shader
/PySpace-master/pyspace/shader.py", line 102, in compile_program
PySpace-master/pyspace/shader.py", line 73, in compile
/PySpace-master/ray_marcher_demo.py", line 253, in <module>

**Comment by Quruzz** [comment]
I have been trying to run the bat file and it's not working. It's not compiling.
![image](https://user-images.githubusercontent.com/21133379/51204642-0ce45480-18d2-11e9-9763-3aa7638778bb.png)
I tried fixing it as it suggested and ended up with a new error.
![image](https://user-images.githubusercontent.com/21133379/51204754-52a11d00-18d2-11e9-8ddd-7b43296f2234.png)

**Comment by zephyren25** [comment]
@Quruzz open a new issue (and use python 2, or the python 3 PR)

**Comment by sharad-s** [comment]
receiving the same issue when trying to run this script unmodified on python2 and python3 on MacOS Sierra

**Comment by HackerPoet** [comment]
I'm pretty sure this issue is the same as #8 and should be resolved now.
