### ISSUE TITLE
Module finding

### ISSUE THREAD

**Issue by kikawet** [HackerPoet/PySpace#3]
![imagen](https://user-images.githubusercontent.com/28111220/51135943-8bda7e00-183b-11e9-9b5a-12daa8de06b8.png)

I know those modules are from the folder next to the file but for some reason it can't find them :/
I'm also using python 3.7.2 so I had issues with the prints too but I just added some ()

**Comment by Brambor** [comment]
I just made it work in Python 3, I could share the code somehow...

**Comment by kikawet** [comment]
you just need to make a pull request so other ppl can get it

**Comment by Brambor** [comment]
Pull request is there! #4
